version: "3.9"

services:
  frontend:
    build: frontend/.
    ports:
      - "5173:5173"

  api-gateway:
    build: backend/peerprep-api-gateway/.
    ports:
      - "8080:8080"
  question-service:
    build: backend/peerprep-question-service/.
    ports:
      - "8082:8082"
  matching-service:
    build: backend/peerprep-matching-service/.
    ports:
      - "8083:8083"
  session-service:
    build: backend/peerprep-session-service/.
    ports:
      - "8081:8081"
