version: "3"

services:
  PeerprepApiGatewayApplication:
    image: "rachelkeh/peerprep-api-gateway-0.0.1.jar"
    build:
      context: ./backend/peerprep-api-gateway
    container_name: peerprep-api-gateway-0.0.1
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "$HOME/.config/gcloud/application_default_credentials.json:/gcp/creds.json:ro"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
  PeerprepQuestionServiceApplication:
    image: "rachelkeh/peerprep-question-service-0.0.1.jar"
    build:
      context: ./backend/peerprep-question-service
    container_name: peerprep-question-service-0.0.1
    ports:
      - "8082:8082"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "$HOME/.config/gcloud/application_default_credentials.json:/gcp/creds.json:ro"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
  PeerprepMatchingServiceApplication:
    image: "rachelkeh/peerprep-matching-service-0.0.1.jar"
    build:
      context: ./backend/peerprep-matching-service
    container_name: peerprep-matching-service-0.0.1.jar
    ports:
      - "8083:8083"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  PeerprepFrontendApplication:
    image: "rachelkeh/peerprep-frontend"
    build:
      context: ./frontend
    container_name: peerprep-frontend
    ports:
      - "5173:5173"
