# This is a basic workflow to help you get started with Actions

name: CD with GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCLOUD_CD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_CD_SERVICE_ACCOUNT }}

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v1
        with:
          deliverables: app.yaml
          version: v1

      - name: Deploy question service
        run: gcloud app deploy
        working-directory: ./backend/peerprep-question-service

      - name: Deploy matching service
        run: gcloud app deploy
        working-directory: ./backend/peerprep-matching-service

      - name: Deploy api gateway service
        run: gcloud app deploy
        working-directory: ./backend/peerprep-api-gateway
